# Artificial Neural Network

In [1]:
# Import Library
import pandas as pd

In [2]:

url = 'https://raw.githubusercontent.com/rc-dbe/bigdatacertification/master/dataset/churn_trasnsformed_new.csv'
df_csv = pd.read_csv(url, sep=',',)


df_csv.head()

,Unnamed: 0,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,1,1,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,1,0,0,1,1,0,0,1,34,...,1,0,1,0,0,1,0,5695,18895.0,0
2,2,1,0,0,1,1,0,0,1,2,...,0,1,0,1,0,1,0,5385,10815.0,1
3,3,1,0,0,1,1,0,0,1,45,...,1,0,1,0,0,1,1,423,184075.0,0
4,4,0,1,0,1,1,0,0,1,2,...,0,1,0,1,0,0,1,707,15165.0,1

In [3]:

df = df_csv.drop("Unnamed: 0", axis=1)
df.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0,1,0,1,0,1,0,1,1,0,...,0,1,0,1,0,0,1,2985,2985.0,0
1,1,0,0,1,1,0,0,1,34,1,...,1,0,1,0,0,1,0,5695,18895.0,0
2,1,0,0,1,1,0,0,1,2,1,...,0,1,0,1,0,1,0,5385,10815.0,1
3,1,0,0,1,1,0,0,1,45,0,...,1,0,1,0,0,1,1,423,184075.0,0
4,0,1,0,1,1,0,0,1,2,1,...,0,1,0,1,0,0,1,707,15165.0,1

In [4]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender_0            7043 non-null   int64
 1   gender_1            7043 non-null   int64
 2   SeniorCitizen_0     7043 non-null   int64
 3   SeniorCitizen_1     7043 non-null   int64
 4   Partner_0           7043 non-null   int64
 5   Partner_1           7043 non-null   int64
 6   Dependents_0        7043 non-null   int64
 7   Dependents_1        7043 non-null   int64
 8   tenure              7043 non-null   int64
 9   PhoneService_0      7043 non-null   int64
 10  PhoneService_1      7043 non-null   int64
 11  MultipleLines_0     7043 non-null   int64
 12  MultipleLines_1     7043 non-null   int64
 13  MultipleLines_2     7043 non-null   int64
 14  InternetService_0   7043 non-null   int64
 15  InternetService_1   7043 non-null   int64
 16  InternetService_2   7043 non-null   int64
 17  OnlineSecurity_0    7043 non-null   int64
 18  OnlineSecurity_1    7043 non-null   int64
 19  OnlineSecurity_2    7043 non-null   int64
 20  OnlineBackup_0      7043 non-null   int64
 21  OnlineBackup_1      7043 non-null   int64
 22  OnlineBackup_2      7043 non-null   int64
 23  DeviceProtection_0  7043 non-null   int64
 24  DeviceProtection_1  7043 non-null   int64
 25  DeviceProtection_2  7043 non-null   int64
 26  TechSupport_0       7043 non-null   int64
 27  TechSupport_1       7043 non-null   int64
 28  TechSupport_2       7043 non-null   int64
 29  StreamingTV_0       7043 non-null   int64
 30  StreamingTV_1       7043 non-null   int64
 31  StreamingTV_2       7043 non-null   int64
 32  StreamingMovies_0   7043 non-null   int64
 33  StreamingMovies_1   7043 non-null   int64
 34  StreamingMovies_2   7043 non-null   int64
 35  Contract_0          7043 non-null   int64
 36  Contract_1          7043 non-null   int64
 37  Contract_2          7043 non-null   int64
 38  PaperlessBilling_0  7043 non-null   int64
 39  PaperlessBilling_1  7043 non-null   int64
 40  PaymentMethod_0     7043 non-null   int64
 41  PaymentMethod_1     7043 non-null   int64
 42  PaymentMethod_2     7043 non-null   int64
 43  MonthlyCharges      7043 non-null   int64
 44  TotalCharges        7043 non-null   float64
 45  Churn               7043 non-null   int64
dtypes: float64(1), int64(45)
memory usage: 2.5 MB

In [5]:

from sklearn.preprocessing import MinMaxScaler


mm_scaler = MinMaxScaler()
column_names = df.columns.tolist()
column_names.remove('Churn')

df[column_names] = mm_scaler.fit_transform(df[column_names])
df.sort_index(inplace=True)
df.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges,Churn
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420,0
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766,0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449,1
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235,0
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465,1

In [6]:
feature = ['Churn']
train_feature = df.drop(feature, axis=1)

train_target = df["Churn"]

In [7]:
train_feature.head(5)

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.013889,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.250169,0.003420
1,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.472222,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.478745,0.021766
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.452598,0.012449
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.625000,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.034076,0.212235
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.027778,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.058030,0.017465

In [8]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(train_feature ,train_target, shuffle = True, test_size=0.3, random_state=1)

In [9]:
X_train.head()

,gender_0,gender_1,SeniorCitizen_0,SeniorCitizen_1,Partner_0,Partner_1,Dependents_0,Dependents_1,tenure,PhoneService_0,...,Contract_0,Contract_1,Contract_2,PaperlessBilling_0,PaperlessBilling_1,PaymentMethod_0,PaymentMethod_1,PaymentMethod_2,MonthlyCharges,TotalCharges
5925,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.277778,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.056343,0.016308
4395,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.958333,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.875169,0.085848
1579,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.166667,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.676957,0.010935
1040,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.194444,1.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.761302,0.014578
1074,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.013889,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.016194,0.000221

In [10]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5), activation = 'relu', solver = 'adam',max_iter= 10000, verbose = True)
mlp = mlp.fit(X_train,y_train)

y_predmlp = mlp.predict(X_test)

Iteration 1, loss = 0.60573699
Iteration 2, loss = 0.58130934
Iteration 3, loss = 0.56819181
Iteration 4, loss = 0.55389200
Iteration 5, loss = 0.53526205
Iteration 6, loss = 0.51483539
Iteration 7, loss = 0.49692434
Iteration 8, loss = 0.47976960
Iteration 9, loss = 0.46725029
Iteration 10, loss = 0.46034370
Iteration 11, loss = 0.45563895
Iteration 12, loss = 0.45249109
Iteration 13, loss = 0.45021556
Iteration 14, loss = 0.44850175
Iteration 15, loss = 0.44730163
Iteration 16, loss = 0.44547899
Iteration 17, loss = 0.44442417
Iteration 18, loss = 0.44347700
Iteration 19, loss = 0.44203196
Iteration 20, loss = 0.44125141
Iteration 21, loss = 0.44035219
Iteration 22, loss = 0.43978222
Iteration 23, loss = 0.43898696
Iteration 24, loss = 0.43837391
Iteration 25, loss = 0.43778824
Iteration 26, loss = 0.43728159
Iteration 27, loss = 0.43676253
Iteration 28, loss = 0.43608971
Iteration 29, loss = 0.43574740
Iteration 30, loss = 0.43534776
Iteration 31, loss = 0.43482042
Iteration 32, loss = 0.43462105
Iteration 33, loss = 0.43421850
Iteration 34, loss = 0.43363929
Iteration 35, loss = 0.43357805
Iteration 36, loss = 0.43301682
Iteration 37, loss = 0.43285366
Iteration 38, loss = 0.43252802
Iteration 39, loss = 0.43218844
Iteration 40, loss = 0.43213818
Iteration 41, loss = 0.43185052
Iteration 42, loss = 0.43141756
Iteration 43, loss = 0.43108668
Iteration 44, loss = 0.43096735
Iteration 45, loss = 0.43051850
Iteration 46, loss = 0.43064618
Iteration 47, loss = 0.43034887
Iteration 48, loss = 0.43003458
Iteration 49, loss = 0.43019123
Iteration 50, loss = 0.42967399
Iteration 51, loss = 0.42969681
Iteration 52, loss = 0.42944844
Iteration 53, loss = 0.42890185
Iteration 54, loss = 0.42876996
Iteration 55, loss = 0.42879009
Iteration 56, loss = 0.42842823
Iteration 57, loss = 0.42857328
Iteration 58, loss = 0.42816791
Iteration 59, loss = 0.42790483
Iteration 60, loss = 0.42775294
Iteration 61, loss = 0.42774565
Iteration 62, loss = 0.42779713
Iteration 63, loss = 0.42763718
Iteration 64, loss = 0.42726436
Iteration 65, loss = 0.42729746
Iteration 66, loss = 0.42687088
Iteration 67, loss = 0.42689925
Iteration 68, loss = 0.42685670
Iteration 69, loss = 0.42666706
Iteration 70, loss = 0.42677631
Iteration 71, loss = 0.42648538
Iteration 72, loss = 0.42634569
Iteration 73, loss = 0.42629600
Iteration 74, loss = 0.42623547
Iteration 75, loss = 0.42659716
Iteration 76, loss = 0.42598957
Iteration 77, loss = 0.42556638
Iteration 78, loss = 0.42617581
Iteration 79, loss = 0.42613247
Iteration 80, loss = 0.42606471
Iteration 81, loss = 0.42553791
Iteration 82, loss = 0.42539458
Iteration 83, loss = 0.42536792
Iteration 84, loss = 0.42554389
Iteration 85, loss = 0.42562154
Iteration 86, loss = 0.42490859
Iteration 87, loss = 0.42551067
Iteration 88, loss = 0.42485750
Iteration 89, loss = 0.42503203
Iteration 90, loss = 0.42553114
Iteration 91, loss = 0.42455713
Iteration 92, loss = 0.42448180
Iteration 93, loss = 0.42442623
Iteration 94, loss = 0.42439715
Iteration 95, loss = 0.42465658
Iteration 96, loss = 0.42478063
Iteration 97, loss = 0.42448123
Iteration 98, loss = 0.42435689
Iteration 99, loss = 0.42447407
Iteration 100, loss = 0.42401032
Iteration 101, loss = 0.42415924
Iteration 102, loss = 0.42399711
Iteration 103, loss = 0.42405613
Iteration 104, loss = 0.42395760
Iteration 105, loss = 0.42386730
Iteration 106, loss = 0.42362395
Iteration 107, loss = 0.42349273
Iteration 108, loss = 0.42421595
Iteration 109, loss = 0.42378185
Iteration 110, loss = 0.42346486
Iteration 111, loss = 0.42345634
Iteration 112, loss = 0.42407596
Iteration 113, loss = 0.42333219
Iteration 114, loss = 0.42327200
Iteration 115, loss = 0.42351126
Iteration 116, loss = 0.42337979
Iteration 117, loss = 0.42359375
Iteration 118, loss = 0.42323522
Iteration 119, loss = 0.42318138
Iteration 120, loss = 0.42301634
Iteration 121, loss = 0.42333971
Iteration 122, loss = 0.42304353
Iteration 123, loss = 0.42285884
Iteration 124, loss = 0.42274408
Iteration 125, loss = 0.42280726
Iteration 126, loss = 0.42298372
Iteration 127, loss = 0.42262150
Iteration 128, loss = 0.42260364
Iteration 129, loss = 0.42299824
Iteration 130, loss = 0.42261433
Iteration 131, loss = 0.42243514
Iteration 132, loss = 0.42227185
Iteration 133, loss = 0.42233793
Iteration 134, loss = 0.42295259
Iteration 135, loss = 0.42220671
Iteration 136, loss = 0.42214884
Iteration 137, loss = 0.42210251
Iteration 138, loss = 0.42205052
Iteration 139, loss = 0.42207461
Iteration 140, loss = 0.42209277
Iteration 141, loss = 0.42189753
Iteration 142, loss = 0.42194785
Iteration 143, loss = 0.42180162
Iteration 144, loss = 0.42210536
Iteration 145, loss = 0.42190879
Iteration 146, loss = 0.42224772
Iteration 147, loss = 0.42176851
Iteration 148, loss = 0.42191428
Iteration 149, loss = 0.42179393
Iteration 150, loss = 0.42175455
Iteration 151, loss = 0.42163722
Iteration 152, loss = 0.42248205
Iteration 153, loss = 0.42144112
Iteration 154, loss = 0.42134345
Iteration 155, loss = 0.42133582
Iteration 156, loss = 0.42177362
Iteration 157, loss = 0.42108961
Iteration 158, loss = 0.42113286
Iteration 159, loss = 0.42103105
Iteration 160, loss = 0.42119062
Iteration 161, loss = 0.42095787
Iteration 162, loss = 0.42080541
Iteration 163, loss = 0.42083667
Iteration 164, loss = 0.42067553
Iteration 165, loss = 0.42072868
Iteration 166, loss = 0.42069284
Iteration 167, loss = 0.42067606
Iteration 168, loss = 0.42057517
Iteration 169, loss = 0.42064336
Iteration 170, loss = 0.42044384
Iteration 171, loss = 0.42093158
Iteration 172, loss = 0.42029277
Iteration 173, loss = 0.42062477
Iteration 174, loss = 0.42063196
Iteration 175, loss = 0.42053502
Iteration 176, loss = 0.42004152
Iteration 177, loss = 0.41998066
Iteration 178, loss = 0.41982887
Iteration 179, loss = 0.41993355
Iteration 180, loss = 0.41990453
Iteration 181, loss = 0.42011109
Iteration 182, loss = 0.42022094
Iteration 183, loss = 0.42042734
Iteration 184, loss = 0.41976169
Iteration 185, loss = 0.41960856
Iteration 186, loss = 0.42011096
Iteration 187, loss = 0.41965960
Iteration 188, loss = 0.41957533
Iteration 189, loss = 0.41990788
Iteration 190, loss = 0.41954914
Iteration 191, loss = 0.41944893
Iteration 192, loss = 0.41998403
Iteration 193, loss = 0.41924252
Iteration 194, loss = 0.41992893
Iteration 195, loss = 0.41953927
Iteration 196, loss = 0.41940070
Iteration 197, loss = 0.41921771
Iteration 198, loss = 0.41991109
Iteration 199, loss = 0.41927864
Iteration 200, loss = 0.41924135
Iteration 201, loss = 0.41933985
Iteration 202, loss = 0.41909193
Iteration 203, loss = 0.41903389
Iteration 204, loss = 0.41936740
Iteration 205, loss = 0.41878175
Iteration 206, loss = 0.41900637
Iteration 207, loss = 0.41886069
Iteration 208, loss = 0.41869732
Iteration 209, loss = 0.41857224
Iteration 210, loss = 0.41860559
Iteration 211, loss = 0.41929629
Iteration 212, loss = 0.41873844
Iteration 213, loss = 0.41866214
Iteration 214, loss = 0.41861655
Iteration 215, loss = 0.41847322
Iteration 216, loss = 0.41878112
Iteration 217, loss = 0.41836927
Iteration 218, loss = 0.41856159
Iteration 219, loss = 0.41834818
Iteration 220, loss = 0.41843486
Iteration 221, loss = 0.41828186
Iteration 222, loss = 0.41828781
Iteration 223, loss = 0.41855885
Iteration 224, loss = 0.41804499
Iteration 225, loss = 0.41837097
Iteration 226, loss = 0.41808949
Iteration 227, loss = 0.41802477
Iteration 228, loss = 0.41816818
Iteration 229, loss = 0.41833051
Iteration 230, loss = 0.41810934
Iteration 231, loss = 0.41784133
Iteration 232, loss = 0.41836535
Iteration 233, loss = 0.41828790
Iteration 234, loss = 0.41817307
Iteration 235, loss = 0.41773909
Iteration 236, loss = 0.41768826
Iteration 237, loss = 0.41777114
Iteration 238, loss = 0.41780029
Iteration 239, loss = 0.41797007
Iteration 240, loss = 0.41774237
Iteration 241, loss = 0.41754292
Iteration 242, loss = 0.41782507
Iteration 243, loss = 0.41778683
Iteration 244, loss = 0.41746514
Iteration 245, loss = 0.41808764
Iteration 246, loss = 0.41767360
Iteration 247, loss = 0.41756602
Iteration 248, loss = 0.41759296
Iteration 249, loss = 0.41725757
Iteration 250, loss = 0.41739090
Iteration 251, loss = 0.41730497
Iteration 252, loss = 0.41754440
Iteration 253, loss = 0.41742697
Iteration 254, loss = 0.41733633
Iteration 255, loss = 0.41738970
Iteration 256, loss = 0.41711757
Iteration 257, loss = 0.41725615
Iteration 258, loss = 0.41723054
Iteration 259, loss = 0.41772852
Iteration 260, loss = 0.41741330
Iteration 261, loss = 0.41693064
Iteration 262, loss = 0.41699839
Iteration 263, loss = 0.41700076
Iteration 264, loss = 0.41700951
Iteration 265, loss = 0.41700853
Iteration 266, loss = 0.41697174
Iteration 267, loss = 0.41685023
Iteration 268, loss = 0.41713894
Iteration 269, loss = 0.41691086
Iteration 270, loss = 0.41658730
Iteration 271, loss = 0.41678201
Iteration 272, loss = 0.41695536
Iteration 273, loss = 0.41662376
Iteration 274, loss = 0.41662653
Iteration 275, loss = 0.41740131
Iteration 276, loss = 0.41652636
Iteration 277, loss = 0.41659157
Iteration 278, loss = 0.41707207
Iteration 279, loss = 0.41661956
Iteration 280, loss = 0.41638486
Iteration 281, loss = 0.41648980
Iteration 282, loss = 0.41637254
Iteration 283, loss = 0.41725965
Iteration 284, loss = 0.41694226
Iteration 285, loss = 0.41669214
Iteration 286, loss = 0.41683807
Iteration 287, loss = 0.41678845
Iteration 288, loss = 0.41638336
Iteration 289, loss = 0.41655488
Iteration 290, loss = 0.41619381
Iteration 291, loss = 0.41643651
Iteration 292, loss = 0.41632906
Iteration 293, loss = 0.41641249
Iteration 294, loss = 0.41606654
Iteration 295, loss = 0.41637400
Iteration 296, loss = 0.41604712
Iteration 297, loss = 0.41612720
Iteration 298, loss = 0.41625357
Iteration 299, loss = 0.41641321
Iteration 300, loss = 0.41601153
Iteration 301, loss = 0.41616906
Iteration 302, loss = 0.41637356
Iteration 303, loss = 0.41656608
Iteration 304, loss = 0.41632366
Iteration 305, loss = 0.41611701
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [11]:
print('Number of Layer =', mlp.n_layers_)
print('Number of Iteration =', mlp.n_iter_)
print('Current loss computed with the loss function =', mlp.loss_)

Number of Layer = 3
Number of Iteration = 305
Current loss computed with the loss function = 0.4161170131138773

In [12]:
from sklearn import metrics


cnf_matrixmlp = metrics.confusion_matrix(y_test, y_predmlp)
cnf_matrixmlp

array([[1394,  191],
       [ 211,  317]])

In [13]:
acc_mlp = metrics.accuracy_score(y_test, y_predmlp)
prec_mlp = metrics.precision_score(y_test, y_predmlp)
rec_mlp = metrics.recall_score(y_test, y_predmlp)
f1_mlp = metrics.f1_score(y_test, y_predmlp)
kappa_mlp = metrics.cohen_kappa_score(y_test, y_predmlp)

print("Accuracy:", acc_mlp)
print("Precision:", prec_mlp)
print("Recall:", rec_mlp)
print("F1 Score:", f1_mlp)
print("Cohens Kappa Score:", kappa_mlp)

Accuracy: 0.8097491717936584
Precision: 0.6240157480314961
Recall: 0.6003787878787878
F1 Score: 0.611969111969112
Cohens Kappa Score: 0.4860125134634701